@EmployeeMaintenance_HostAddress = https://localhost:44373/api/v1.0

GET {{EmployeeMaintenance_HostAddress}}/employee/1
Accept: application/json
EM-API-KEY: a3f5c9d8e2b4f1c6a7d9e0b3c4d5f6a7
###

GET {{EmployeeMaintenance_HostAddress}}/employee
Accept: application/json
EM-API-KEY: a3f5c9d8e2b4f1c6a7d9e0b3c4d5f6a7
###

POST {{EmployeeMaintenance_HostAddress}}/employee
Content-Type: application/json
Accept: application/json
EM-API-KEY: a3f5c9d8e2b4f1c6a7d9e0b3c4d5f6a7

{
  "name": "Teste123",
  "lastName": "Da silva",
  "hireDate": "2024-12-20",
  "departmentId": 1,
  "phone": "54 9999-9999",
  "address": "Rua XYZ"
}

###

PUT {{EmployeeMaintenance_HostAddress}}/employee/2
Content-Type: application/json
Accept: application/json
EM-API-KEY: a3f5c9d8e2b4f1c6a7d9e0b3c4d5f6a7

{
  "name": "Tessss5te",
  "lastName": "Da silva",
  "hireDate": "2024-12-10",
  "departmentId": 2,
  "phone": "54 9999-9999",
  "address": "Rua XYZ"
}

###

DELETE {{EmployeeMaintenance_HostAddress}}/employee/3
Accept: application/json
EM-API-KEY: a3f5c9d8e2b4f1c6a7d9e0b3c4d5f6a7

###

GET {{EmployeeMaintenance_HostAddress}}/department
Accept: application/json

###

PATCH {{EmployeeMaintenance_HostAddress}}/employee/1/department/3
Accept: application/json